#! /bin/bash

# Check and create virtualenv
if [ ! -d ".venv" ]
then
    virtualenv -p python3 .venv
fi

source .venv/bin/activate

# Check and install requirements
diff -B <(pip freeze | tr '[:upper:]' '[:lower:]' | cut -d= -f1 | sort) \
        <(tr '[:upper:]' '[:lower:]' < requirements.txt | cut -d= -f1 | sort)

if [ $? -ne 0 ]
then
  pip install -r requirements.txt
fi

# Run application
export FLASK_APP='app.py'
flask run
